version: '3'
services:
  mariadb:
    image: mariadb:latest
    restart: always
    container_name: docker_mariadb
    networks:
      relution-network:
        aliases:
          - mariadb-docker
    environment:
      - MYSQL_DATABASE=relution
      - MYSQL_ROOT_PASSWORD=%MYSQL_ROOT_PASSWORD%
      - MYSQL_USER=relution
      - MYSQL_PASSWORD=%MYSQL_PASSWORD%
    expose:
      - '3306'
    volumes:
      - 'mariadb:/var/lib/mysql'
      - 'C:\Program Files\relution\relution.cnf:/etc/mysql/conf.d/relution.cnf'
  mongodb:
    image: mongo:latest
    restart: always
    container_name: docker_mongodb
    networks:
      relution-network:
        aliases:
          - mongodb-docker
    environment:
      - MONGO_INITDB_ROOT_USERNAME=relution
      - MONGO_INITDB_ROOT_PASSWORD=%MONGODB_ROOT_PASSWORD%
      - MONGO_INITDB_DATABASE=relution
    expose:
      - '27017'
    volumes:
      - 'mongodb:/data/db'
  relution:
    image: relution/relution:latest
    restart: always
    container_name: docker_relution
    networks:
      relution-network:
        aliases:
          - relution-docker
    depends_on:
      - mariadb
      - mongodb
    links:
      - mariadb
      - mongodb
    environment:
      - TZ=UTC
      - DATABASE_TYPE=mysql
      - DATABASE_URL=jdbc:mariadb://mariadb-docker/relution?useServerPrepStmts=true
      - DATABASE_USER=relution
      - DATABASE_PWD=%MYSQL_PASSWORD%
      - HOSTNAME=%EXT_HOSTNAME_URL%
      - ORGA_NAME=%ORG_UNIQUE_NAME%
      - ORGA_FULLNAME=%ORG_DISPLAY_NAME%
      - ORGA_ADMIN_USERNAME=%ADM_USERNAME%
      - ORGA_ADMIN_PASSWORD=%ADM_PASSWORD%
      - ORGA_ADMIN_GIVENNAME=%ADM_FIRST_NAME%
      - ORGA_ADMIN_SURNAME=%ADM_LAST_NAME%
      - ORGA_ADMIN_EMAIL=%ADM_EMAIL%
      - ORGA_REPLYTOMAIL=%ADM_EMAIL%
      - MONGO_DATABASE=relution
      - MONGO_HOST=mongodb-docker
      - MONGO_PORT=27017
      - SMTP_HOST=%SMTP_HOSTNAME%
    expose:
      - '8080'
      - '8099'
  nginx:
    image: nginx:stable
    restart: always
    container_name: docker_nginx
    networks:
      relution-network:
        aliases:
          - nginx-docker
    depends_on:
      - relution
    links:
      - relution
    environment:
     - NGINX_HOST=%EXT_HOSTNAME%
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - 'C:\Program Files\relution\relution-nginx.conf:/etc/nginx/conf.d/relution-nginx.conf'
     - 'C:\Program Files\relution\server.pem:/etc/nginx/server.pem'
     - 'C:\Program Files\relution\server.key:/etc/nginx/server.key'

volumes:
  mariadb:
  mongodb:

networks:
  relution-network:
    external:
      name: nat